require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

def all_pods
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson', modular_headers: true
  pod 'MMKV', :modular_headers => true
  pod 'MMKVCore', :modular_headers => true
  $RNFirebaseAnalyticsWithoutAdIdSupport = true

  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

abstract_target 'defaults' do

  all_pods

  target 'Rocket.Chat'
  target 'NotificationService'
end

$static_framework = [ 
  'WatermelonDB',
  'simdjson'
]
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
        Pod::BuildType.static_library # >= 1.9
      end
    end
  end
end

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    # config[:reactNativePath],
    # :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] = "NO"
      
      # Add SecureStorage headers to search paths for react-native-webview
      if target.name == 'react-native-webview'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['HEADER_SEARCH_PATHS'] << '$(SRCROOT)/..'
      end
    end
  end

  # Xcode 26's clang rejects fmt 11.0.2's consteval format-string path
  # ("call to consteval function ... is not a constant expression"). A -D compiler
  # flag can't fix it because base.h redefines FMT_USE_CONSTEVAL unconditionally,
  # so patch the vendored header to force consteval off.
  fmt_base_h = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
  fmt_marker = 'Xcode 26 consteval workaround'
  if File.exist?(fmt_base_h)
    fmt_contents = File.read(fmt_base_h)
    fmt_anchor = "#endif\n#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval"
    if !fmt_contents.include?(fmt_marker) && fmt_contents.include?(fmt_anchor)
      fmt_contents.sub!(
        fmt_anchor,
        "#endif\n// #{fmt_marker}: force-disable fmt consteval format-string checks.\n#undef FMT_USE_CONSTEVAL\n#define FMT_USE_CONSTEVAL 0\n#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval"
      )
      File.chmod(0644, fmt_base_h) # CocoaPods marks pod headers read-only
      File.write(fmt_base_h, fmt_contents)
      Pod::UI.puts "[fmt] Patched base.h to disable consteval (#{fmt_marker})"
    end
  end

  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end
end
